### ISSUE TITLE
Stacktrace while generating preview with nextcloud on mp3 file

### ISSUE THREAD

**Issue by Aureliolo** [ChristophWurst/ID3Parser#9]
Hi, 

I am trying to generate previews of all my files and it seems that this extension/plugin throws an error with some mp3 files. 
Im running newest nextcloud 25.0.2 with PHP 8.1.

Stacktrace: 
```
An unhandled exception has been thrown:
ValueError: strpos(): Argument #3 ($offset) must be contained in argument #1 ($haystack) in /var/www/nextcloud/3rdparty/christophwurst/id3parser/src/getID3/Tags/getid3_id3v2.php:1728
Stack trace:
#0 /var/www/nextcloud/3rdparty/christophwurst/id3parser/src/getID3/Tags/getid3_id3v2.php(1728): strpos()
#1 /var/www/nextcloud/3rdparty/christophwurst/id3parser/src/getID3/Tags/getid3_id3v2.php(338): ID3Parser\getID3\Tags\getid3_id3v2->ParseID3v2Frame()
#2 /var/www/nextcloud/3rdparty/christophwurst/id3parser/src/getID3/getid3.php(164): ID3Parser\getID3\Tags\getid3_id3v2->Analyze()
#3 /var/www/nextcloud/3rdparty/christophwurst/id3parser/src/ID3Parser.php(20): ID3Parser\getID3\getid3->analyze()
#4 /var/www/nextcloud/lib/private/Preview/MP3.php(51): ID3Parser\ID3Parser->analyze()
#5 /var/www/nextcloud/lib/private/Preview/GeneratorHelper.php(65): OC\Preview\MP3->getThumbnail()
#6 /var/www/nextcloud/lib/private/Preview/Generator.php(343): OC\Preview\GeneratorHelper->getThumbnail()
#7 /var/www/nextcloud/lib/private/Preview/Generator.php(162): OC\Preview\Generator->getMaxPreview()
#8 /var/www/nextcloud/lib/private/PreviewManager.php(200): OC\Preview\Generator->generatePreviews()
#9 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(234): OC\PreviewManager->generatePreviews()
#10 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(216): OCA\PreviewGenerator\Command\Generate->parseFile()
#11 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(214): OCA\PreviewGenerator\Command\Generate->parseFolder()
#12 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(214): OCA\PreviewGenerator\Command\Generate->parseFolder()
#13 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(214): OCA\PreviewGenerator\Command\Generate->parseFolder()
#14 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(194): OCA\PreviewGenerator\Command\Generate->parseFolder()
#15 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(140): OCA\PreviewGenerator\Command\Generate->generateUserPreviews()
#16 /var/www/nextcloud/lib/private/User/Manager.php(660): OCA\PreviewGenerator\Command\Generate->OCA\PreviewGenerator\Command\{closure}()
#17 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(141): OC\User\Manager->callForSeenUsers()
#18 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\PreviewGenerator\Command\Generate->execute()
#19 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#20 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#21 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#22 /var/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#23 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#24 /var/www/nextcloud/occ(11): require_once('...')
```

The file in question that causes it:
[09 - Burn Me Slow.zip](https://github.com/ChristophWurst/ID3Parser/files/10302486/09.-.Burn.Me.Slow.zip)

Hope this was the right place to open this issue if not please let me know :)

**Comment by ChristophWurst** [comment]
It might be worth checking https://github.com/nextcloud/server for earlier reports. This repo isn't actively maintained.

**Comment by Aureliolo** [comment]
Thanks for the reply! 

Didn't find anything related there but will gladly open an issue on the main repo if this one isn't actively maintained :)
